(function(global){
  'use strict';
  const THREE=global.THREE;
  if(!THREE||!global.PacVu3DViewer||!global.S001_getLayout)return;
  const PAPER=.4,U=.3527778112205911,TOL=.05,clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),smooth=v=>{v=clamp(v,0,1);return v*v*(3-2*v);};
  function cfg(){const c=typeof getCfgS001==='function'?getCfgS001():{};return Object.assign({},c,{W:+c.W||298,D:+c.D||61,H:+c.H||292,viewMode:'Insert Only'});}
  function flatten(d){const ns='http://www.w3.org/2000/svg',svg=document.createElementNS(ns,'svg'),p=document.createElementNS(ns,'path');p.setAttribute('d',d);svg.append(p);document.body.append(svg);const len=p.getTotalLength(),out=[],at=n=>{const q=p.getPointAtLength(n);return{x:q.x,y:q.y};},dev=(q,a,b)=>{const x=b.x-a.x,y=b.y-a.y,ll=x*x+y*y;if(!ll)return Math.hypot(q.x-a.x,q.y-a.y);const t=clamp(((q.x-a.x)*x+(q.y-a.y)*y)/ll,0,1);return Math.hypot(q.x-a.x-x*t,q.y-a.y-y*t);};function split(da,a,db,b,n){const dm=(da+db)/2,m=at(dm);if(n<18&&dev(m,a,b)>TOL/U){split(da,a,dm,m,n+1);split(dm,m,db,b,n+1);return;}out.push(a);}const seeds=Math.max(12,Math.ceil(len/18));for(let i=0;i<seeds;i++)split(len*i/seeds,at(len*i/seeds),len*(i+1)/seeds,at(len*(i+1)/seeds),0);svg.remove();return out;}
  function clip(c,b){const k=1e4,cv=a=>a.map(q=>({X:Math.round(q.x*k),Y:Math.round(q.y*k)})),sol=new global.ClipperLib.Paths(),op=new global.ClipperLib.Clipper();op.AddPath(cv(c),global.ClipperLib.PolyType.ptSubject,true);op.AddPath(cv([{x:b[0],y:b[1]},{x:b[2],y:b[1]},{x:b[2],y:b[3]},{x:b[0],y:b[3]}]),global.ClipperLib.PolyType.ptClip,true);op.Execute(global.ClipperLib.ClipType.ctIntersection,sol,global.ClipperLib.PolyFillType.pftNonZero,global.ClipperLib.PolyFillType.pftNonZero);return(sol[0]||[]).map(q=>({x:q.X/k,y:q.Y/k}));}
  function build(){
    const c=cfg(),layout=global.S001_getLayout(c,c),part=layout.rawParts.insertPad,s=part.spec,signature=[c.W,c.D,c.H,c.productFitPreset||'baseline'].join(':');
    const pw=(v,a,b)=>{let i=0;if(v>=a[a.length-1])i=a.length-2;else while(i<a.length-2&&v>a[i+1])i++;const t=(v-a[i])/(a[i+1]-a[i]);return b[i]+(b[i+1]-b[i])*t;},mp=(x,y)=>({x:pw(x,s.sourceX,s.targetX),y:pw(y,s.sourceY,s.targetY)}),X=x=>mp(x,2500).x,Y=y=>mp(2200,y).y;
    const x0=X(1814.913),x1=X(1894.283),x2=X(2670.976),x3=X(2750.346),y0=Y(2135.677),y1=Y(2215.047),y2=Y(2923.709),y3=Y(3003.079),pad=.06;
    const regions={center:[x1-pad,y1-pad,x2+pad,y2+pad],top:[x1,y0,x2,y1+pad],bottom:[x1,y2-pad,x2,y3],left:[x0,y1,x1+pad,y2],right:[x2-pad,y1,x3,y2]};
    const outer=flatten(part.fillPath),contours=Object.fromEntries(Object.entries(regions).map(([n,b])=>[n,clip(outer,b)])),productCutElements=part.holeElements||[],b=part.bounds,center={x:(b.minX+b.maxX)/2,y:(b.minY+b.maxY)/2},world=q=>new THREE.Vector2((q.x-center.x)*U,(center.y-q.y)*U);
    const viewer=global.PacVu3DViewer.createModal({id:'s001Insert3dModal',badge:'S001 · Insert Pad · Stage 1'}),{modal,stage}=viewer,scene=new THREE.Scene();scene.background=new THREE.Color(global.PacVu3DTheme.colors.background);const camera=global.PacVu3DViewer.createPerspectiveCamera(THREE,{W:s.W,D:s.D,H:s.H}),renderer=global.PacVu3DViewer.createRenderer(THREE);stage.prepend(renderer.domElement);const controls=new global.PacVuOrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.screenSpacePanning=true;scene.add(new THREE.HemisphereLight(global.PacVu3DTheme.hemisphereLight.skyColor,global.PacVu3DTheme.hemisphereLight.groundColor,global.PacVu3DTheme.hemisphereLight.intensity));const sun=new THREE.DirectionalLight(global.PacVu3DTheme.directionalLight.color,global.PacVu3DTheme.directionalLight.intensity);sun.position.fromArray(global.PacVu3DTheme.directionalLight.position);sun.castShadow=true;scene.add(sun);const floor=new THREE.Mesh(new THREE.PlaneGeometry(1200,1200),new THREE.ShadowMaterial({color:0x3f3933,opacity:.3}));floor.receiveShadow=true;floor.position.z=-45;scene.add(floor);const grid=new THREE.GridHelper(global.PacVu3DTheme.grid.size,global.PacVu3DTheme.grid.divisions,global.PacVu3DTheme.grid.centerColor,global.PacVu3DTheme.grid.lineColor);grid.rotation.x=Math.PI/2;grid.position.z=floor.position.z+.02;scene.add(grid);global.PacVu3DViewer.standardizeEnvironment({renderer,scene,controls,floor,grid});
    const mats=global.PacVu3DViewer.createBoardMaterials(THREE);mats[2]=mats[2].clone();mats[2].color.copy(mats[0].color);const root=new THREE.Group();scene.add(root);const pieces={},hinges=[];
    function make(n){let o=contours[n].map(world);if(!THREE.ShapeUtils.isClockWise(o))o.reverse();const sh=new THREE.Shape(o);const g=new THREE.ExtrudeGeometry(sh,{depth:PAPER,bevelEnabled:false,steps:1,curveSegments:1});g.translate(0,0,-PAPER/2);global.PacVu3DViewer.assignBoardFaceMaterials(g,PAPER,'exterior');const m=new THREE.Mesh(g,mats);m.castShadow=m.receiveShadow=true;const z=contours[n].reduce((a,q)=>({x:a.x+q.x,y:a.y+q.y}),{x:0,y:0}),l=contours[n].length;pieces[n]={mesh:m,center:new THREE.Vector3((z.x/l-center.x)*U,(center.y-z.y/l)*U,0)};return m;}
    Object.keys(contours).forEach(make);
    const guideCanvas=document.createElement('canvas');guideCanvas.width=2048;guideCanvas.height=Math.max(1024,Math.round(2048*(y2-y1)/(x2-x1)));const guideCtx=guideCanvas.getContext('2d');guideCtx.clearRect(0,0,guideCanvas.width,guideCanvas.height);guideCtx.strokeStyle='#79b99a';guideCtx.globalAlpha=.9;guideCtx.lineWidth=1.35*(x2-x1)/guideCanvas.width;guideCtx.lineCap='round';guideCtx.lineJoin='round';guideCtx.setTransform(guideCanvas.width/(x2-x1),0,0,guideCanvas.height/(y2-y1),-x1*guideCanvas.width/(x2-x1),-y1*guideCanvas.height/(y2-y1));productCutElements.forEach(e=>{if(!e.d)return;guideCtx.stroke(new Path2D(e.d));});const guideTexture=new THREE.CanvasTexture(guideCanvas);guideTexture.colorSpace=THREE.SRGBColorSpace;guideTexture.minFilter=THREE.LinearFilter;guideTexture.magFilter=THREE.LinearFilter;guideTexture.generateMipmaps=false;const guideMaterial=global.PacVu3DViewer.createOverlayMaterial(THREE,{map:guideTexture,transparent:true,depthWrite:false,toneMapped:false});const guide=new THREE.Mesh(new THREE.PlaneGeometry((x2-x1)*U,(y2-y1)*U),guideMaterial),guideCenter=world({x:(x1+x2)/2,y:(y1+y2)/2});guide.position.set(guideCenter.x,guideCenter.y,PAPER/2+.018);guide.renderOrder=20;guide.userData.s001ProductCutGuide=true;pieces.center.mesh.add(guide);
    const point=(x,y)=>{const q=mp(x,y);return new THREE.Vector3((q.x-center.x)*U,(center.y-q.y)*U,0);},sheet=new THREE.Group();root.add(sheet);sheet.add(pieces.center.mesh);
    function attach(n,a,b2,start){const p=point(a[0],a[1]),q=point(b2[0],b2[1]),h=new THREE.Group();h.position.copy(p);sheet.add(h);const f=new THREE.Group();f.position.copy(p).multiplyScalar(-1);h.add(f);f.add(pieces[n].mesh);const axis=q.clone().sub(p).normalize(),rad=pieces[n].center.clone().sub(p),natural=new THREE.Vector3().crossVectors(axis,rad).z>=0?-1:1;hinges.push({o:h,axis,angle:Math.PI/2*natural,start,end:start+.28});}
    attach('top',[1894.283,2215.047],[2670.976,2215.047],.05);attach('right',[2670.976,2215.047],[2670.976,2923.709],.18);attach('bottom',[2670.976,2923.709],[1894.283,2923.709],.31);attach('left',[1894.283,2923.709],[1894.283,2215.047],.44);
    function pose(v){global.PacVu3DViewer.syncProgress(viewer,v*100,'Insert Pad Assembly');hinges.forEach(h=>h.o.quaternion.setFromAxisAngle(h.axis,h.angle*smooth((v-h.start)/(h.end-h.start))));}function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}const fit=t=>global.PacVu3DViewer.fitObject(root,camera,controls,t);viewer.range.oninput=()=>pose(+viewer.range.value/100);viewer.range.onchange=()=>fit('iso');modal.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>fit(b.dataset.view));modal.querySelector('[data-close]').onclick=()=>modal.classList.remove('open');modal.querySelector('[data-shadow]').onclick=e=>{floor.visible=!floor.visible;sun.castShadow=floor.visible;e.currentTarget.textContent=floor.visible?'Shadows On':'Shadows Off';};modal.querySelector('[data-download]').onclick=()=>renderer.domElement.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='S001_INSERT_PAD.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});const ob=new ResizeObserver(resize);ob.observe(stage);resize();pose(0);fit('top');let live=true;(function loop(){if(!live)return;requestAnimationFrame(loop);controls.update();renderer.render(scene,camera);}());return{signature,root,pose,open(){modal.classList.add('open');resize();fit('top');},destroy(){live=false;ob.disconnect();controls.dispose?.();root.traverse(o=>o.geometry?.dispose());guideTexture.dispose();guideMaterial.dispose();mats.forEach(m=>m.dispose());renderer.dispose();modal.remove();}};
  }
  let app;global.S001Insert3D={open(){const c=cfg(),sig=[c.W,c.D,c.H,c.productFitPreset||'baseline'].join(':');if(!app||app.signature!==sig){app?.destroy();app=build();}app.open();},getCompleted(){const c=cfg(),sig=[c.W,c.D,c.H,c.productFitPreset||'baseline'].join(':');if(!app||app.signature!==sig){app?.destroy();app=build();}app.pose(1);return app.root;}};
}(window));
