(function(global){
  'use strict';
  const THREE=global.THREE;if(!THREE||!global.PacVu3DViewer||!global.S001_getLayout)return;
  const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),smooth=v=>{v=clamp(v,0,1);return v*v*(3-2*v);};
  function cfg(){const c=typeof getCfgS001==='function'?getCfgS001():{};return Object.assign({},c,{W:+c.W||298,D:+c.D||61,H:+c.H||292,viewMode:'All Parts'});}
  function build(){
    const c=cfg(),layout=global.S001_getLayout(c,c),outer=layout.rawParts.outerSleeve.spec,tray=layout.rawParts.innerTray.spec,pad=layout.rawParts.insertPad.spec,signature=[c.W,c.D,c.H,c.productFitPreset||'baseline'].join(':');
    const OW=+outer.W||298,OD=+outer.H||292,OH=+outer.D||61,TW=+tray.W||290,TD=+tray.H||280,TH=+tray.D||55,PW=+pad.W||274,PD=+pad.H||250,PH=+pad.D||28,t=.65;
    const viewer=global.PacVu3DViewer.createModal({id:'s001Assembly3dModal',badge:'S001 · Assembly'}),{modal,stage}=viewer,scene=new THREE.Scene();scene.background=new THREE.Color(global.PacVu3DTheme.colors.background);const camera=global.PacVu3DViewer.createPerspectiveCamera(THREE,{W:OW,D:OH,H:OD}),renderer=global.PacVu3DViewer.createRenderer(THREE);stage.prepend(renderer.domElement);const controls=new global.PacVuOrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.screenSpacePanning=true;scene.add(new THREE.HemisphereLight(global.PacVu3DTheme.hemisphereLight.skyColor,global.PacVu3DTheme.hemisphereLight.groundColor,global.PacVu3DTheme.hemisphereLight.intensity));const sun=new THREE.DirectionalLight(global.PacVu3DTheme.directionalLight.color,global.PacVu3DTheme.directionalLight.intensity);sun.position.fromArray(global.PacVu3DTheme.directionalLight.position);sun.castShadow=true;scene.add(sun);const floor=new THREE.Mesh(new THREE.PlaneGeometry(1500,1500),new THREE.ShadowMaterial({color:0x3f3933,opacity:.3}));floor.rotation.x=0;floor.receiveShadow=true;floor.position.z=-OH/2-15;scene.add(floor);const grid=new THREE.GridHelper(global.PacVu3DTheme.grid.size,global.PacVu3DTheme.grid.divisions,global.PacVu3DTheme.grid.centerColor,global.PacVu3DTheme.grid.lineColor);grid.rotation.x=Math.PI/2;grid.position.z=floor.position.z+.02;scene.add(grid);global.PacVu3DViewer.standardizeEnvironment({renderer,scene,controls,floor,grid});
    const white=new THREE.MeshLambertMaterial({color:0xffffff,side:THREE.DoubleSide}),kraft=new THREE.MeshLambertMaterial({color:0xc9ad7e,side:THREE.DoubleSide}),edge=new THREE.MeshLambertMaterial({color:0xf2f2f0});const root=new THREE.Group();scene.add(root);
    const box=(w,h,d,mat=white)=>{const m=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat);m.castShadow=m.receiveShadow=true;return m;};
    const sleeve=new THREE.Group();root.add(sleeve);const top=box(OW,OD,t),bottom=box(OW,OD,t),left=box(t,OD,OH),right=box(t,OD,OH);top.position.z=OH/2;bottom.position.z=-OH/2;left.position.set(-OW/2,0,0);right.position.set(OW/2,0,0);sleeve.add(top,bottom,left,right);const innerTop=box(OW-2*t,OD-2,0.05,kraft);innerTop.position.z=OH/2-t-.04;sleeve.add(innerTop);
    const trayGroup=new THREE.Group(),trayShell=new THREE.Group();trayGroup.add(trayShell);const trayBase=box(TW,TD,t,kraft),trayL=box(t,TD,TH,white),trayR=box(t,TD,TH,white),trayBack=box(TW,t,TH,white),trayFront=box(TW,t,TH,white);trayBase.position.z=-TH/2;trayL.position.set(-TW/2,0,0);trayR.position.set(TW/2,0,0);trayBack.position.set(0,TD/2,0);trayFront.position.set(0,-TD/2,0);trayShell.add(trayBase,trayL,trayR,trayBack,trayFront);root.add(trayGroup);
    const insert=new THREE.Group(),padTop=box(PW,PD,t,white);insert.add(padTop);[['x',-PW/2],['x',PW/2]].forEach(a=>{const m=box(t,PD,PH,white);m.position[a[0]]=a[1];m.position.z=-PH/2;insert.add(m);});[['y',-PD/2],['y',PD/2]].forEach(a=>{const m=box(PW,t,PH,white);m.position[a[0]]=a[1];m.position.z=-PH/2;insert.add(m);});trayGroup.add(insert);
    const elems=layout.rawParts.insertPad.holeElements||[],canvas=document.createElement('canvas');canvas.width=1600;canvas.height=Math.round(1600*PD/PW);const ctx=canvas.getContext('2d'),pb=layout.rawParts.insertPad.bounds,sx=canvas.width/(pb.maxX-pb.minX),sy=canvas.height/(pb.maxY-pb.minY);ctx.clearRect(0,0,canvas.width,canvas.height);ctx.strokeStyle='#79b99a';ctx.globalAlpha=.9;ctx.lineWidth=1.2/sx;ctx.lineCap='round';ctx.lineJoin='round';ctx.setTransform(sx,0,0,sy,-pb.minX*sx,-pb.minY*sy);elems.forEach(e=>e.d&&ctx.stroke(new Path2D(e.d)));const texture=new THREE.CanvasTexture(canvas);texture.colorSpace=THREE.SRGBColorSpace;texture.generateMipmaps=false;texture.minFilter=THREE.LinearFilter;const guideMat=global.PacVu3DViewer.createOverlayMaterial(THREE,{map:texture,transparent:true,depthWrite:false,toneMapped:false}),guide=new THREE.Mesh(new THREE.PlaneGeometry(PW,PD),guideMat);guide.position.z=t/2+.012;guide.renderOrder=20;padTop.add(guide);
    function pose(v){global.PacVu3DViewer.syncProgress(viewer,v*100,'S001 Assembly');const drop=smooth((v-.05)/.35),slide=smooth((v-.43)/.52),outsideY=-(OD+TD/2+45);trayGroup.position.y=outsideY*(1-slide);trayGroup.position.z=-OH/2+TH/2+t;insert.position.z=PH+(115*(1-drop));}
    function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}const fit=v=>global.PacVu3DViewer.fitObject(root,camera,controls,v);viewer.range.oninput=()=>pose(+viewer.range.value/100);viewer.range.onchange=()=>fit('iso');modal.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>fit(b.dataset.view));modal.querySelector('[data-close]').onclick=()=>modal.classList.remove('open');modal.querySelector('[data-shadow]').onclick=e=>{floor.visible=!floor.visible;sun.castShadow=floor.visible;e.currentTarget.textContent=floor.visible?'Shadows On':'Shadows Off';};modal.querySelector('[data-download]').onclick=()=>renderer.domElement.toBlob(blob=>{if(!blob)return;const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='S001_ASSEMBLY.png';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);});const ob=new ResizeObserver(resize);ob.observe(stage);resize();pose(0);fit('iso');let live=true;(function loop(){if(!live)return;requestAnimationFrame(loop);controls.update();renderer.render(scene,camera);}());return{signature,open(){modal.classList.add('open');resize();fit('iso');},destroy(){live=false;ob.disconnect();controls.dispose?.();root.traverse(o=>o.geometry?.dispose());texture.dispose();guideMat.dispose();white.dispose();kraft.dispose();edge.dispose();renderer.dispose();modal.remove();}};
  }
  let app;global.S001Assembly3D={open(){const c=cfg(),sig=[c.W,c.D,c.H,c.productFitPreset||'baseline'].join(':');if(!app||app.signature!==sig){app?.destroy();app=build();}app.open();}};
}(window));
