// T010_3d.js - source-accurate Flat inspection in the approved T006 Viewer environment.
(function(global){
'use strict';
if(!global.T010_getLayout)return;
const EPS=.001;
// Trace the authored red strokes in perimeter order. The layout fill is a
// union of inferred faces/convex hulls and is NOT the cutting boundary.
function sourceCutOutline(layout){
  const cut=layout.cutElements.map(global.T010_elementPoints),out=[];
  const append=(points)=>out.push(...points.map(p=>({x:p.x,y:p.y})));
  append(cut[1]);append(cut[15]);append(cut[0]);
  // Paired horizontal strokes overlap in the source: retain their union
  // without doubling back along the top edge.
  append(cut[9].slice(0,-1));append(cut[10].slice(1));
  // Keep the tear-off strip attached: bridge its left edge with board,
  // rather than treating the perforation's rounded return as a cutout.
  append(cut[6]);
  const lowerTip=cut[6][cut[6].length-1],upperTip=cut[23][cut[23].length-1],stripX=cut[6][cut[6].length-2].x;
  append([{x:stripX,y:lowerTip.y},{x:stripX,y:upperTip.y}]);
  append(cut[23].slice().reverse());
  append(cut[5].slice(0,-1));append(cut[14].slice(1));
  append(global.T010_elementPoints(layout.punchElements[0]));
  append(cut[13]);append(cut[11].slice(0,-1));append(cut[12].slice(1));
  append(cut[4]);append(cut[21]);append(cut[20]);append(cut[19]);
  append(cut[16]);append(cut[3]);append(cut[17]);append(cut[8]);append(cut[7]);append(cut[2]);
  return out.filter((p,i)=>!i||Math.hypot(p.x-out[i-1].x,p.y-out[i-1].y)>.001);
}
function clipEdge(points,inside,intersect){const result=[];if(!points.length)return result;let previous=points[points.length-1],previousInside=inside(previous);points.forEach(current=>{const currentInside=inside(current);if(currentInside!==previousInside)result.push(intersect(previous,current));if(currentInside)result.push(current);previous=current;previousInside=currentInside;});return result;}
function atX(a,b,x){const t=Math.abs(b.x-a.x)<1e-9?0:(x-a.x)/(b.x-a.x);return{x,y:a.y+(b.y-a.y)*t};}
function atY(a,b,y){const t=Math.abs(b.y-a.y)<1e-9?0:(y-a.y)/(b.y-a.y);return{x:a.x+(b.x-a.x)*t,y};}
function clipRect(points,b){let p=points.slice();p=clipEdge(p,q=>q.x>=b.minX-EPS,(a,c)=>atX(a,c,b.minX));p=clipEdge(p,q=>q.x<=b.maxX+EPS,(a,c)=>atX(a,c,b.maxX));p=clipEdge(p,q=>q.y>=b.minY-EPS,(a,c)=>atY(a,c,b.minY));p=clipEdge(p,q=>q.y<=b.maxY+EPS,(a,c)=>atY(a,c,b.maxY));return p;}
function area(points){let v=0;for(let i=0,j=points.length-1;i<points.length;j=i++)v+=points[j].x*points[i].y-points[i].x*points[j].y;return Math.abs(v/2);}
function clipLine(points,a,b,keepSign){const side=p=>(b.x-a.x)*(p.y-a.y)-(b.y-a.y)*(p.x-a.x),result=[];if(!points.length)return result;let previous=points[points.length-1],previousValue=side(previous)*keepSign,previousInside=previousValue>=-EPS;points.forEach(current=>{const currentValue=side(current)*keepSign,currentInside=currentValue>=-EPS;if(currentInside!==previousInside){const t=previousValue/(previousValue-currentValue);result.push({x:previous.x+(current.x-previous.x)*t,y:previous.y+(current.y-previous.y)*t});}if(currentInside)result.push(current);previous=current;previousValue=currentValue;previousInside=currentInside;});return result;}
function buildContract(input){const spec=global.T010_getSpec(input||{W:80,D:72,H:190}),layout=global.T010_getLayout(spec.W,spec.D,spec.H),g=layout.grid,panelPaths=[sourceCutOutline(layout)],columns=[['back',g.xBackL,g.xBackR],['sideLeft',g.xBackR,g.xSideLR],['front',g.xSideLR,g.xFrontR],['sideRight',g.xFrontR,g.xSideRR]],panels=[];
function region(id,role,x1,x2,y1,y2){const polygons=panelPaths.map(path=>clipRect(path,{minX:x1,maxX:x2,minY:y1,maxY:y2})).filter(p=>p.length>=3&&area(p)>.2);panels.push({id,role,polygons});}
function largestRegion(id,role,x1,x2,y1,y2){const candidates=panelPaths.map(path=>clipRect(path,{minX:x1,maxX:x2,minY:y1,maxY:y2})).filter(p=>p.length>=3&&area(p)>.2),polygons=candidates.length?[candidates.reduce((largest,p)=>area(p)>area(largest)?p:largest)]:[];panels.push({id,role,polygons});}
function faceRegion(id,role,x1,x2,y1,y2){const candidates=panelPaths.map(face=>clipRect(face,{minX:x1,maxX:x2,minY:y1,maxY:y2})).filter(p=>p.length>=3&&area(p)>.2),merged=candidates.length?global.T010_unionFaces(candidates):[],polygons=merged.length?[merged.reduce((largest,p)=>area(p)>area(largest)?p:largest)]:[];panels.push({id,role,polygons});}
region('glue','bodyGlue',g.xGlueL,g.xBackL,g.yBodyTop,g.yBodyBottom);
columns.forEach(([id,x1,x2])=>largestRegion(id,'body',x1,x2,g.yBodyTop,g.yBodyBottom));
columns.forEach(([id,x1,x2])=>faceRegion('top'+id[0].toUpperCase()+id.slice(1),'top',x1,x2,layout.dielineBounds.minY,g.yBodyTop));
faceRegion('bottomSideLeft','bottomReceiverLeft',g.xBackR,g.xSideLR,g.yBodyBottom,layout.dielineBounds.maxY);faceRegion('bottomSideRight','bottomReceiverRight',g.xFrontR,g.xSideRR,g.yBodyBottom,layout.dielineBounds.maxY);
function splitBottom(id,role,x1,x2,foldIndex,receiverEdge){const source=panelPaths.map(face=>clipRect(face,{minX:x1,maxX:x2,minY:g.yBodyBottom,maxY:layout.dielineBounds.maxY})).filter(p=>p.length>=3&&area(p)>.2),line=global.T010_linePoints(layout.foldElements[foldIndex]),a={x:line[0],y:line[1]},b={x:line[2],y:line[3]},probe={x:receiverEdge-0.05,y:g.yBodyBottom+Math.max(1,spec.bottomLength*.08)},probeSign=((b.x-a.x)*(probe.y-a.y)-(b.y-a.y)*(probe.x-a.x))>=0?1:-1,wingFaces=source.map(p=>clipLine(p,a,b,probeSign)).filter(p=>p.length>=3&&area(p)>.2),mainFaces=source.map(p=>clipLine(p,a,b,-probeSign)).filter(p=>p.length>=3&&area(p)>.2),wing=wingFaces.length?[wingFaces.reduce((largest,p)=>area(p)>area(largest)?p:largest)]:[],main=mainFaces.length?[mainFaces.reduce((largest,p)=>area(p)>area(largest)?p:largest)]:[];panels.push({id,role,polygons:main},{id:id+'Wing',role:'bottomWing',polygons:wing});return Object.freeze({foldIndex,a:Object.freeze(a),b:Object.freeze(b),main:id,wing:id+'Wing'});}
const backSplit=splitBottom('bottomBack','bottomLockA',g.xBackL,g.xBackR,4,g.xBackR),frontSplit=splitBottom('bottomFront','bottomLockB',g.xSideLR,g.xFrontR,15,g.xFrontR);
return Object.freeze({code:'T010',dimensions:{W:spec.W,D:spec.D,H:spec.H},layout,panels:Object.freeze(panels),bodySeam:Object.freeze({inside:'glue',outside:'sideRight'}),bottomLock:Object.freeze({back:backSplit,front:frontSplit,contacts:Object.freeze([{wing:'bottomBackWing',receiver:'bottomSideLeft'},{wing:'bottomFrontWing',receiver:'bottomSideRight'}])}),states:Object.freeze({flat:0,bodySeam:.55,bottomInsert:1})});}
function createMaster(input){const THREE=global.THREE,Viewer=global.PacVu3DViewer;if(!THREE||!Viewer||!global.PacVuOrbitControls)throw new Error('T010 shared 3D Viewer unavailable.');const contract=buildContract(input),bounds=contract.layout.dielineBounds,center={x:bounds.minX+bounds.width/2,y:bounds.minY+bounds.height/2},thickness=.45,to3=p=>new THREE.Vector3(p.x-center.x,center.y-p.y,0);
const flatCutPaths=[sourceCutOutline(contract.layout)];
const {modal,stage}=Viewer.createModal({id:'t0103dModal',badge:'T010 · Flat to Body Seam POC'}),scene=new THREE.Scene();scene.background=new THREE.Color(global.PacVu3DTheme.colors.background);const camera=Viewer.createPerspectiveCamera(THREE,contract.dimensions),renderer=Viewer.createRenderer(THREE);renderer.setPixelRatio(Math.min(global.devicePixelRatio||1,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;stage.prepend(renderer.domElement);const controls=new global.PacVuOrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.dampingFactor=.075;
scene.add(new THREE.HemisphereLight(global.PacVu3DTheme.hemisphereLight.skyColor,global.PacVu3DTheme.hemisphereLight.groundColor,global.PacVu3DTheme.hemisphereLight.intensity));const sun=new THREE.DirectionalLight(global.PacVu3DTheme.directionalLight.color,global.PacVu3DTheme.directionalLight.intensity);sun.position.fromArray(global.PacVu3DTheme.directionalLight.position);sun.castShadow=true;scene.add(sun);const floor=new THREE.Mesh(new THREE.PlaneGeometry(1800,1800),new THREE.ShadowMaterial({color:0x3f3933,opacity:.3}));floor.receiveShadow=true;floor.position.z=-2;scene.add(floor);const grid=new THREE.GridHelper(global.PacVu3DTheme.grid.size,global.PacVu3DTheme.grid.divisions,global.PacVu3DTheme.grid.centerColor,global.PacVu3DTheme.grid.lineColor);grid.rotation.x=Math.PI/2;grid.position.z=global.PacVu3DTheme.grid.z;scene.add(grid);Viewer.standardizeEnvironment({renderer,scene,controls,floor,grid});
const existing=Viewer.createBoardMaterials(THREE);existing[1].color.set(global.PacVu3DTheme.colors.interior);existing[2].color.setHex(0xf2f0ed);existing[2].name='T010 light paper fold edge';const whitePaperboard=global.PacVuWhitePaperboard?.createMaterials(THREE,renderer,{sourceMaterials:existing}),whiteMaterials=whitePaperboard?.materials?[whitePaperboard.materials[0],existing[1],existing[2]]:existing,materialSets={existing,white:whiteMaterials};let materialMode='white';const root=new THREE.Group();root.name='T010 body-seam assembly';scene.add(root);const pieces=new Map();
const exactFlat=new THREE.Group();exactFlat.name='T010 exact 2D Cut sheet';root.add(exactFlat);flatCutPaths.forEach((polygon,index)=>{if(polygon.length<3||area(polygon)<.2)return;let outline=polygon.map(p=>new THREE.Vector2(p.x-center.x,center.y-p.y));if(!THREE.ShapeUtils.isClockWise(outline))outline=outline.slice().reverse();const shape=new THREE.Shape(outline);shape.closePath();const geometry=new THREE.ExtrudeGeometry(shape,{depth:thickness,bevelEnabled:false,steps:1,curveSegments:48});geometry.translate(0,0,-thickness/2);global.PacVuWhitePaperboard?.applyPhysicalUV(THREE,geometry,{offsetX:center.x,offsetY:center.y});Viewer.assignBoardFaceMaterials(geometry,thickness,'interior');geometry.computeVertexNormals();const mesh=new THREE.Mesh(geometry,materialSets[materialMode]);mesh.name='exact-flat-cut-'+(index+1);mesh.castShadow=mesh.receiveShadow=true;exactFlat.add(mesh);});
const flatDetails=new THREE.Group();flatDetails.name='T010 exact source cut and punch details';root.add(flatDetails);const cutDetailMaterial=new THREE.LineBasicMaterial({color:0x68563d,transparent:true,opacity:.72,depthTest:false}),punchDetailMaterial=new THREE.LineBasicMaterial({color:0x68563d,transparent:true,opacity:.6,depthTest:false});function addSourceDetail(element,material,name){const points=global.T010_elementPoints(element);if(points.length<2)return;const geometry=new THREE.BufferGeometry().setFromPoints(points.map(p=>to3(p).setZ(thickness/2+.02))),line=new THREE.Line(geometry,material);line.name=name;line.renderOrder=50;flatDetails.add(line);}addSourceDetail(contract.layout.cutElements[22],cutDetailMaterial,'source-u-cut');contract.layout.punchElements.forEach((element,index)=>addSourceDetail(element,punchDetailMaterial,'source-punch-'+(index+1)));
contract.panels.forEach(def=>{const group=new THREE.Group();group.name=def.id;def.polygons.forEach((polygon,index)=>{if(polygon.length<3||area(polygon)<.2)return;let outline=polygon.map(p=>new THREE.Vector2(p.x-center.x,center.y-p.y));if(!THREE.ShapeUtils.isClockWise(outline))outline=outline.slice().reverse();const shape=new THREE.Shape(outline);shape.closePath();const geometry=new THREE.ExtrudeGeometry(shape,{depth:thickness,bevelEnabled:false,steps:1,curveSegments:24});geometry.translate(0,0,-thickness/2);global.PacVuWhitePaperboard?.applyPhysicalUV(THREE,geometry,{offsetX:center.x,offsetY:center.y});Viewer.assignBoardFaceMaterials(geometry,thickness,'interior');geometry.computeVertexNormals();const mesh=new THREE.Mesh(geometry,materialSets[materialMode]);const isBottomLayer=def.role.indexOf('bottom')===0;mesh.name=def.id+(index?'-'+index:'');mesh.castShadow=mesh.receiveShadow=!isBottomLayer;if(def.role==='bottomWing')mesh.position.z=thickness*.55;group.add(mesh);});pieces.set(def.id,group);});
const standPoint=to3({x:contract.layout.grid.xBackL,y:contract.layout.grid.yBodyBottom}),standHinge=new THREE.Group();standHinge.position.copy(standPoint);root.add(standHinge);const sheet=new THREE.Group();sheet.position.copy(standPoint).multiplyScalar(-1);standHinge.add(sheet);sheet.add(pieces.get('back'));const frames=new Map([['back',sheet]]),hinges=[];
function attach(id,parentId,childId,a,b,range,foldDegrees){const parent=frames.get(parentId),child=pieces.get(childId);if(!parent||!child)return;const p=to3(a),q=to3(b),hinge=new THREE.Group();hinge.name=id;hinge.position.copy(p);parent.add(hinge);const frame=new THREE.Group();frame.position.copy(p).multiplyScalar(-1);hinge.add(frame);frame.add(child);frames.set(childId,frame);const axis=q.clone().sub(p).normalize(),box=new THREE.Box3().setFromObject(child),childCenter=box.getCenter(new THREE.Vector3()),sign=new THREE.Vector3().crossVectors(axis,childCenter.sub(p)).z>=0?1:-1;hinges.push({id,hinge,axis,radians:Math.PI/180*(foldDegrees||90)*sign,range});}
const g=contract.layout.grid;attach('back-glue','back','glue',{x:g.xBackL,y:g.yBodyBottom},{x:g.xBackL,y:g.yBodyTop},[.02,.15]);attach('back-sideLeft','back','sideLeft',{x:g.xBackR,y:g.yBodyTop},{x:g.xBackR,y:g.yBodyBottom},[.05,.18]);attach('sideLeft-front','sideLeft','front',{x:g.xSideLR,y:g.yBodyTop},{x:g.xSideLR,y:g.yBodyBottom},[.10,.23]);attach('front-sideRight','front','sideRight',{x:g.xFrontR,y:g.yBodyTop},{x:g.xFrontR,y:g.yBodyBottom},[.15,.28]);
const topEdges={topBack:[g.xBackL,g.xBackR],topSideLeft:[g.xBackR,g.xSideLR],topFront:[g.xSideLR,g.xFrontR],topSideRight:[g.xFrontR,g.xSideRR]};
[['back','topBack'],['sideLeft','topSideLeft'],['front','topFront'],['sideRight','topSideRight']].forEach(([body,top])=>{const edge=topEdges[top],range=top==='topBack'?[.84,.90]:top==='topFront'?[.92,1]:[.78,.84];attach('top.'+top,body,top,{x:edge[0],y:g.yBodyTop},{x:edge[1],y:g.yBodyTop},range,90);});
const topMarks=new THREE.Group();topMarks.name='T010 lid punch impressions';pieces.get('topFront').add(topMarks);
const grooveMaterial=new THREE.MeshStandardMaterial({color:0x5f594f,roughness:1,metalness:0,transparent:true,opacity:.28,depthTest:true,depthWrite:false});
const grooveAxis=new THREE.Vector3(0,1,0);
function addLidGroove(element,name,radius,includeSegment){const points=global.T010_elementPoints(element);if(points.length<2)return;const group=new THREE.Group(),grooveZ=-thickness/2+radius*.7;group.name=name;for(let i=1;i<points.length;i++){if(includeSegment&&!includeSegment(points[i-1],points[i]))continue;const start=to3(points[i-1]).setZ(grooveZ),end=to3(points[i]).setZ(grooveZ),delta=end.clone().sub(start),length=delta.length();if(length<.001)continue;const geometry=new THREE.CylinderGeometry(radius,radius,length,8,1,false),mesh=new THREE.Mesh(geometry,grooveMaterial);mesh.position.copy(start).add(end).multiplyScalar(.5);mesh.quaternion.setFromUnitVectors(grooveAxis,delta.normalize());mesh.renderOrder=60;group.add(mesh);}topMarks.add(group);}
contract.layout.punchElements.forEach((element,index)=>{const isEndCap=index===contract.layout.punchElements.length-1;addLidGroove(element,'lid-punch-impression-'+(index+1),.05,isEndCap?(a,b)=>Math.abs(a.y-b.y)<.001:null);});
addLidGroove(contract.layout.cutElements[22],'lid-slot-cut-impression',.045);
attach('back-bottom','back','bottomBack',{x:g.xBackL,y:g.yBodyBottom},{x:g.xBackR,y:g.yBodyBottom},[.48,.55],180);attach('front-bottom','front','bottomFront',{x:g.xSideLR,y:g.yBodyBottom},{x:g.xFrontR,y:g.yBodyBottom},[.56,.63],180);attach('sideLeft-bottom','sideLeft','bottomSideLeft',{x:g.xBackR,y:g.yBodyBottom},{x:g.xSideLR,y:g.yBodyBottom},[.64,.71],180);attach('sideRight-bottom','sideRight','bottomSideRight',{x:g.xFrontR,y:g.yBodyBottom},{x:g.xSideRR,y:g.yBodyBottom},[.72,.79],180);
function attachWing(id,parentId,childId,a,b,range){const parent=frames.get(parentId),child=pieces.get(childId);if(!parent||!child)return;const p=to3(a),q=to3(b),hinge=new THREE.Group();hinge.name=id;hinge.position.copy(p);parent.add(hinge);const frame=new THREE.Group();frame.position.copy(p).multiplyScalar(-1);hinge.add(frame);frame.add(child);frames.set(childId,frame);const axis=q.clone().sub(p).normalize();hinges.push({id,hinge,axis,radians:-Math.PI*(new THREE.Vector3().crossVectors(axis,new THREE.Box3().setFromObject(child).getCenter(new THREE.Vector3()).sub(p)).z>=0?1:-1),range});}
attachWing('back-wing-diagonal','bottomBack','bottomBackWing',contract.bottomLock.back.a,contract.bottomLock.back.b,[.34,.40]);attachWing('front-wing-diagonal','bottomFront','bottomFrontWing',contract.bottomLock.front.a,contract.bottomLock.front.b,[.42,.48]);
const frameBases=new Map();['bottomBack','bottomFront','bottomSideLeft','bottomSideRight'].forEach(id=>{const frame=frames.get(id);if(frame)frameBases.set(id,frame.position.clone());});
const bondCopies=new Map();contract.bottomLock.contacts.forEach(contact=>{const original=pieces.get(contact.wing),receiver=frames.get(contact.receiver),receiverPiece=pieces.get(contact.receiver);if(!original||!receiver||!receiverPiece)return;const copy=original.clone(true);copy.name=contact.wing+'.bonded-to-'+contact.receiver;copy.visible=false;original.parent.add(copy);copy.position.copy(original.position);copy.quaternion.copy(original.quaternion);copy.scale.copy(original.scale);bondCopies.set(contact.wing,{original,copy,receiver,receiverPiece,bonded:false});});
function setBottomBonded(active){bondCopies.forEach(link=>{if(active&&!link.bonded){link.original.updateWorldMatrix(true,false);link.original.parent.add(link.copy);link.copy.position.copy(link.original.position);link.copy.quaternion.copy(link.original.quaternion);link.copy.scale.copy(link.original.scale);root.updateMatrixWorld(true);link.receiver.attach(link.copy);link.copy.position.z=link.receiverPiece.position.z-thickness*.18;link.bonded=true;}if(!active)link.bonded=false;link.original.visible=!active;link.copy.visible=active;});}
// Physical slit shading, never the red/green drafting palette in 3D.
cutDetailMaterial.color.setHex(0x68563d);cutDetailMaterial.opacity=.72;
const foldLines=[];
const clamp=v=>Math.max(0,Math.min(1,v)),smooth=v=>{v=clamp(v);return v*v*(3-2*v);},phase=(v,r)=>smooth((v-r[0])/(r[1]-r[0]));
function pose(value){
const progress=clamp(value),bottomProgress=clamp(progress/.68),isFlat=progress<=EPS;
const press=phase(bottomProgress,[.80,.90]),release=phase(bottomProgress,[.90,1]),pressCycle=press*(1-release),bond=phase(bottomProgress,[.88,.90]);
// A fast slider jump must still pass through the pressed contact pose. The
// diagonal lock wings are transferred to the inside receiver only there.
if(bottomProgress>.900001&&[...bondCopies.values()].some(link=>!link.bonded))pose(.68*.90);
exactFlat.visible=isFlat;flatDetails.visible=isFlat;pieces.forEach(piece=>piece.visible=!isFlat);
hinges.forEach(item=>{const isTop=item.id.indexOf('top.')===0;let amount=phase(isTop?progress:bottomProgress,item.range);if(item.id.indexOf('-wing-diagonal')>0)amount=Math.max(amount,bond);let angle=item.radians*amount;if(item.id==='back-sideLeft'||item.id==='front-sideRight')angle+=item.radians*pressCycle;else if(item.id==='sideLeft-front'||item.id==='back-glue')angle*=1-pressCycle;if(item.id==='back-bottom'||item.id==='sideLeft-bottom'||item.id==='front-bottom'||item.id==='sideRight-bottom')angle*=1-.5*release;item.hinge.quaternion.setFromAxisAngle(item.axis,angle);});
const layerPhases={bottomBack:phase(bottomProgress,[.48,.55]),bottomFront:phase(bottomProgress,[.56,.63]),bottomSideLeft:phase(bottomProgress,[.64,.71]),bottomSideRight:phase(bottomProgress,[.72,.79])};
Object.entries(layerPhases).forEach(([id,amount])=>{const frame=frames.get(id),base=frameBases.get(id),piece=pieces.get(id);if(!frame||!base||!piece)return;const stack=(id==='bottomBack'||id==='bottomFront')?.012:.024;frame.position.z=base.z-stack*amount;piece.visible=!isFlat&&pressCycle<.98;});
if(bond>=.999)setBottomBonded(true);else if(bottomProgress<.88)setBottomBonded(false);
bondCopies.forEach(link=>{link.original.visible=!isFlat&&!link.bonded&&pressCycle<.98;link.copy.visible=!isFlat&&link.bonded&&pressCycle<.98&&progress<=.68;});
['sideLeft','front','sideRight','glue'].forEach((id,index)=>{const piece=pieces.get(id);if(piece)piece.position.z=-thickness*(index+1)*pressCycle;});
const lidStack=phase(progress,[.78,1]),lidOffsets={topSideLeft:.18,topBack:.38,topSideRight:.18,topFront:-.62};
['topSideLeft','topBack','topSideRight','topFront'].forEach((id,index)=>{const piece=pieces.get(id);if(piece)piece.position.z=-thickness*(index+1.25)*pressCycle+thickness*lidOffsets[id]*lidStack;});
standHinge.quaternion.setFromAxisAngle(new THREE.Vector3(1,0,0),Math.PI/2*phase(progress,[.68,.75]));
root.position.z=0;root.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(root);if(!box.isEmpty())root.position.z=grid.position.z+thickness/2-box.min.z;
modal.querySelector('.assembly-fill').style.width=Math.round(progress*100)+'%';const active=progress<.18?0:progress<.48?1:progress<.60?2:progress<.75?3:4;modal.querySelectorAll('.assembly-labels span').forEach((node,index)=>node.classList.toggle('active',index<=active));}
function setMaterialMode(mode){materialMode=mode==='existing'?'existing':'white';pieces.forEach(group=>group.traverse(object=>{if(object.isMesh)object.material=materialSets[materialMode];}));topMarks.traverse(object=>{if(object.isMesh)object.material=grooveMaterial;});exactFlat.traverse(object=>{if(object.isMesh)object.material=materialSets[materialMode];});modal.querySelectorAll('[data-material-mode]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.materialMode===materialMode)));}const materialControls=document.createElement('div');materialControls.className='m001-3d-views pacvu-viewer__views t006-material-controls';materialControls.style.right='118px';materialControls.innerHTML='<button type="button" class="btn light" data-material-mode="existing">Existing Material</button><button type="button" class="btn light" data-material-mode="white" aria-pressed="true">White Paperboard</button>';stage.append(materialControls);materialControls.querySelectorAll('[data-material-mode]').forEach(button=>button.onclick=()=>setMaterialMode(button.dataset.materialMode));
const slider=modal.querySelector('input');slider.value='0';slider.disabled=false;slider.title='T010 T004 assembly sequence';slider.oninput=()=>pose(Number(slider.value)/100);slider.onchange=()=>pose(Number(slider.value)/100);
const labels=modal.querySelector('.assembly-labels');labels.innerHTML='<span class="active">Flat</span><span>Body</span><span>Bottom</span><span>Press + Bond</span><span>Closed</span>';labels.style.gridTemplateColumns='repeat(5,1fr)';
let gridVisible=grid.visible;const gridButton=modal.querySelector('[data-grid]');function syncGrid(){grid.visible=gridVisible;if(gridButton){gridButton.setAttribute('aria-pressed',String(gridVisible));gridButton.textContent=gridVisible?'Grid On':'Grid Off';}}if(gridButton)gridButton.onclick=()=>{gridVisible=!gridVisible;syncGrid();};syncGrid();let shadows=true;modal.querySelector('[data-shadow]').onclick=e=>{shadows=!shadows;renderer.shadowMap.enabled=shadows;sun.castShadow=shadows;floor.visible=shadows;e.currentTarget.textContent=shadows?'Shadows On':'Shadows Off';};const view=type=>Viewer.fitObject(root,camera,controls,type);modal.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>view(button.dataset.view));modal.querySelector('[data-close]').onclick=()=>modal.classList.remove('open');modal.querySelector('[data-download]').onclick=()=>Viewer.downloadPNG({renderer,scene,camera,controls,filename:'T010_Bottom_Complete.png'});pose(0);
const whiteStudio=global.PacVuWhiteStudio?.create({scene,camera,controls,renderer,root,sun,floor,grid})||null;function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();}const observer=new ResizeObserver(resize);observer.observe(stage);resize();let live=true,hasInitialView=false;(function loop(){if(!live)return;requestAnimationFrame(loop);controls.update();renderer.render(scene,camera);})();return{contract,signature:[contract.dimensions.W,contract.dimensions.D,contract.dimensions.H].join(':'),open(){modal.classList.add('open');resize();if(!hasInitialView){view('iso');hasInitialView=true;}},destroy(){live=false;observer.disconnect();whiteStudio?.dispose?.();whitePaperboard?.dispose?.();controls.dispose?.();renderer.dispose();modal.remove();}};}
let master=null;function open(state,input){const cfg=input||(typeof global.getCfgT010==='function'?global.getCfgT010():{W:80,D:72,H:190}),signature=[cfg.W,cfg.D,cfg.H].join(':');if(!master||master.signature!==signature){master?.destroy();master=createMaster(cfg);}master.open();return master;}global.T010_3D_BUILD_CONTRACT=buildContract;global.T010_3D_MASTER=Object.freeze({buildContract,create:createMaster,open});function trigger(){const toolbar=document.querySelector('.toolbar')||document.body;if(document.getElementById('t010-3d-btn'))return;const button=document.createElement('button');button.id='t010-3d-btn';button.type='button';button.style.display='none';button.onclick=()=>open('flat');toolbar.appendChild(button);}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',trigger);else trigger();
})(window);
