// T007_layout.js - exact source-SVG coordinate mapping
const T007_SOURCE_GRID=Object.freeze({x:[52.831,93.857,406.665,633.436,944.244,1171.013],y:[278.646,440.724,1078.514,1232.737]});
function T007_num(v){return +(+v).toFixed(4)}
function T007_piece(v,s,t){if(v<=s[0])return t[0]+(v-s[0])*(t[1]-t[0])/(s[1]-s[0]);for(let i=0;i<s.length-1;i++)if(v<=s[i+1])return t[i]+(v-s[i])*(t[i+1]-t[i])/(s[i+1]-s[i]);let n=s.length-1;return t[n]+(v-s[n])*(t[n]-t[n-1])/(s[n]-s[n-1])}
function T007_mapper(s){const glue=s.D*(14.47/80),top=s.D*(57.18/80),bottom=s.D*(54.4/80),tx=[0,glue,glue+s.W,glue+s.W+s.D,glue+s.W+s.D+s.W,glue+s.W+s.D+s.W+s.D],ty=[0,top,top+s.H,top+s.H+bottom],sx=T007_SOURCE_GRID.x,sy=T007_SOURCE_GRID.y;return{x:v=>T007_piece(v,sx,tx),y:v=>T007_piece(v,sy,ty),point(x,y){return{x:T007_piece(x,sx,tx),y:T007_piece(y,sy,ty)}},grid:{xGlueL:tx[0],xBackL:tx[1],xBackR:tx[2],xSideLR:tx[3],xFrontR:tx[4],xSideRR:tx[5],yTop:ty[0],yBodyTop:ty[1],yBodyBottom:ty[2],yBottom:ty[3]}}}
function T007_transform(e,m){if(/^<path/.test(e)){return '<path d="'+T001_transformPathD(T001_attr(e,'d'),m)+'"/>'}const a=m.point(+T001_attr(e,'x1'),+T001_attr(e,'y1')),b=m.point(+T001_attr(e,'x2'),+T001_attr(e,'y2'));return '<line x1="'+T007_num(a.x)+'" y1="'+T007_num(a.y)+'" x2="'+T007_num(b.x)+'" y2="'+T007_num(b.y)+'"/>'}
function T007_bounds(elements){const pts=[];elements.forEach(e=>pts.push(...T001_flattenPathD(T001_elementToPathD(e))));const b=T001_polygonBounds(pts);return{...b,width:b.maxX-b.minX,height:b.maxY-b.minY}}
function T007_joinOuterCut(elements){const segs=elements.map(e=>T001_flattenPathD(T001_elementToPathD(e))),points=segs.shift().slice();while(segs.length){const end=points[points.length-1];let bestIndex=0,bestReverse=false,bestDistance=Infinity;segs.forEach((segment,index)=>{const first=segment[0],last=segment[segment.length-1],firstDistance=Math.hypot(end.x-first.x,end.y-first.y),lastDistance=Math.hypot(end.x-last.x,end.y-last.y);if(firstDistance<bestDistance){bestDistance=firstDistance;bestIndex=index;bestReverse=false}if(lastDistance<bestDistance){bestDistance=lastDistance;bestIndex=index;bestReverse=true}});const next=segs.splice(bestIndex,1)[0];points.push(...(bestReverse?next.slice().reverse():next))}return T001_polygonToPath(points)}
function T007_getLayout(input){const spec=T007_getSpec(input),mapper=T007_mapper(spec),outerCut=T007_SOURCE_OUTER_CUT.map(e=>T007_transform(e,mapper)),foldElements=T007_SOURCE_FOLD.map(e=>T007_transform(e,mapper)),tearCut=spec.tearOffEnabled?T007_SOURCE_TEAR_CUT.map(e=>T007_transform(e,mapper)):[],tearPerf=spec.tearOffEnabled?T007_SOURCE_TEAR_PERF.map(e=>T007_transform(e,mapper)):[],liftPerf=spec.liftTabsEnabled?T007_SOURCE_LIFT_PERF.map(e=>T007_transform(e,mapper)):[],liftFold=spec.liftTabsEnabled?T007_SOURCE_LIFT_FOLD.map(e=>T007_transform(e,mapper)):[],bleedElement=T007_transform(T007_SOURCE_BLEED,mapper),bleedPath=T001_attr(bleedElement,'d'),bleedPoints=T001_flattenPathD(bleedPath),dielineBounds=T007_bounds(outerCut),bleedBounds=T001_polygonBounds(bleedPoints);bleedBounds.width=bleedBounds.maxX-bleedBounds.minX;bleedBounds.height=bleedBounds.maxY-bleedBounds.minY;const fillPath=T007_joinOuterCut(outerCut);const g=mapper.grid,glueTop=mapper.point(52.831,454.972),glueBottom=mapper.point(52.831,1055.29),mid=(g.yBodyTop+g.yBodyBottom)/2,labels=[['Glue',(g.xGlueL+g.xBackL)/2,mid],['Back',(g.xBackL+g.xBackR)/2,mid],['Side(L)',(g.xBackR+g.xSideLR)/2,mid],['Front',(g.xSideLR+g.xFrontR)/2,mid],['Side(R)',(g.xFrontR+g.xSideRR)/2,mid]] .map(v=>({name:v[0],x:v[1],y:v[2]}));return{spec,mapper,grid:g,outerCut,cutElements:outerCut.concat(tearCut),foldElements:foldElements.concat(liftFold),perforationElements:tearPerf.concat(liftPerf),tearCut,tearPerf,liftPerf,liftFold,bleedElement,bleedPath,fillPath,dielineBounds,bleedBounds,bounds:dielineBounds,labels,glueFillPath:'M '+g.xBackL+' '+g.yBodyTop+' L '+glueTop.x+' '+glueTop.y+' L '+glueBottom.x+' '+glueBottom.y+' L '+g.xBackL+' '+g.yBodyBottom+' Z'};}
